### ISSUE TITLE
单独使用相机  拍照完成后 ，拍摄按钮还在

### ISSUE THREAD

**Issue by SetAdapter** [joker-fu/EasyPhotos#10]
单独使用相机  拍照完成后 ，拍摄按钮还在，不做操作责停留大约1-2秒正常拿到照片回到展示界面  如果再次重复点击按钮  会闪退
在以下机型为必现  多种机型 都能重现
设备机型 OPPO PBAT00  vivo Y81s
系统版本 Android 8.1.0

**Comment by SetAdapter** [comment]
没办法只能选择使用系统相机 就没这个问题

**Comment by joker-fu** [comment]
提供下依赖版本信息，异常日志

**Comment by SetAdapter** [comment]
版本   'com.joker.HuanTanSheng:EasyPhotos:2.5.1' 

单独使用相机 拍照完成后 ，拍摄按钮还在 不做操作责停留大约1-2秒正常拿到照片回到展示界面  如果再次重复点击按钮 会闪退  异常信息：

java.lang.RuntimeException: takePicture failed
        at android.hardware.Camera.native_takePicture(Native Method)
        at android.hardware.Camera.takePicture(Camera.java:1660)
        at android.hardware.Camera.takePicture(Camera.java:1594)
        at com.huantansheng.cameralibrary.CameraInterface.takePicture(CameraInterface.java:490)
        at com.huantansheng.cameralibrary.state.PreviewState.capture(PreviewState.java:59)
        at com.huantansheng.cameralibrary.state.CameraMachine.capture(CameraMachine.java:96)
        at com.huantansheng.cameralibrary.JCameraView$3.takePictures(JCameraView.java:194)
        at com.huantansheng.cameralibrary.CaptureLayout$2.takePictures(CaptureLayout.java:154)
        at com.huantansheng.cameralibrary.CaptureButton$2.onAnimationEnd(CaptureButton.java:239)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1064)
        at android.view.Choreographer.doCallbacks(Choreographer.java:878)
        at android.view.Choreographer.doFrame(Choreographer.java:791)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1052)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:210)
        at android.app.ActivityThread.main(ActivityThread.java:7080)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
