### ISSUE TITLE
拍照返回崩溃

### ISSUE THREAD

**Issue by 823546371** [joker-fu/EasyPhotos#25]
品牌：vivo
android： 8.1
错误日志：
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=11, result=-1, data=Intent { (has extras) }} to activity {com.huantansheng.easyphotos.ui.EasyPhotosActivity}: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
at android.app.ActivityThread.deliverResults(ActivityThread.java:4565)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4609)
at android.app.ActivityThread.-wrap20(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:192)
at android.app.ActivityThread.main(ActivityThread.java:6896)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
Caused by: java.lang.RuntimeException: EasyPhotos拍照保存的图片不存在
at com.huantansheng.easyphotos.ui.EasyPhotosActivity.onActivityResult(EasyPhotosActivity.java:306)
at android.app.Activity.dispatchActivityResult(Activity.java:7408)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4561)

初步排查怀疑是getpathUri这个方法不兼容8.1，望作者查看修复

**Comment by huaxuanHan** [comment]
在Android7.1.2上面出现同样的问题，拍照崩溃，找不到文件路径，还望作者百忙之中抽空修复，十分感谢您的辛苦付出

**Comment by huaxuanHan** [comment]
今天把代码下载下来测试了一下，发现是getPathByUri的问题，在Android5、11、13是可以的，7、8、9都不行，7/8/9上面获取的文件路径前面加的有/camera_photos，我目前是判断一下，把/camera_photos去掉，剩余的路径直接返回，这样就可以了，简单粗暴，但是不知道这样的判断是不是严谨

**Comment by huaxuanHan** [comment]
在鸿蒙系统手机上面能获取到文件路径，但是图片显示不出来，这个不知道该怎么解决
