### ISSUE TITLE
选择图片的时候偶尔会出现地址获取不到报空指针，频率还挺高，使用版本是2.4.7造成的，目前升级到2.5.0看源码似乎也没做null校验，麻烦作者看看多谢了

### ISSUE THREAD

**Issue by tangzhenkun** [joker-fu/EasyPhotos#3]
崩溃日志内容=java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
at com.huantansheng.easyphotos.ui.adapter.PreviewPhotosFragmentAdapter.onBindViewHolder(PreviewPhotosFragmentAdapter.java:45)
at com.huantansheng.easyphotos.ui.adapter.PreviewPhotosFragmentAdapter.onBindViewHolder(PreviewPhotosFragmentAdapter.java:22)
at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
at android.view.View.measure(View.java:23454)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:23454)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6834)

at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)

**Comment by joker-fu** [comment]
手机型号 Android版本 应用targetSdk这些是多少呢？

**Comment by tangzhenkun** [comment]
targetSdkVersion = 28
三星 android 9 该问题不是必现

**Comment by joker-fu** [comment]
你那边能断点看到是path还是type是null吗？代码里相同的判断很多？比如进来的选择界面，可能的话帮忙定位下问题
